/**
* VkRadixSort written by Mirco Werner: https://github.com/MircoWerner/VkRadixSort
* Based on implementation of Intel's Embree: https://github.com/embree/embree/blob/v4.0.0-ploc/kernels/rthwif/builder/gpu/sort.h
*/
#version 460
#extension GL_GOOGLE_include_directive: enable

// constraints
// 1. WORKGROUP_SIZE must be a multiple of 32
// 2. WORKGROUP_SIZE >= RADIX_SORT_BINS
// 3. RADIX_SORT_BINS >= SUBGROUP_SIZE
// Adjusting the RADIX_SORT_BINS requires updating the scheduling of the passes on the host side!
layout (local_size_x_id = 0, local_size_x = 256) in; // 256 is the default value, you can update specialization constant 0 from host side
#define WORKGROUP_SIZE gl_WorkGroupSize.x
layout (constant_id = 1) const uint RADIX_SORT_BINS = 256; // 256 is the default value, you can update specialization constant 1 from host side

layout (push_constant, std430) uniform PushConstants {
    uint g_num_elements;
    uint g_shift;
    uint g_num_workgroups;
    uint g_num_blocks_per_workgroup;
};

layout (std430, set = 0, binding = 0) buffer elements_in {
    uint g_elements_in[];
};

layout (std430, set = 0, binding = 1) buffer histograms {
    // [histogram_of_workgroup_0 | histogram_of_workgroup_1 | ... ]
    uint g_histograms[]; // |g_histograms| = RADIX_SORT_BINS * #WORKGROUPS
};

shared uint[RADIX_SORT_BINS] histogram;

void main() {
    // initialize histogram
    if (gl_LocalInvocationID.x < RADIX_SORT_BINS) {
        histogram[gl_LocalInvocationID.x] = 0U;
    }
    barrier();

    for (uint index = 0; index < g_num_blocks_per_workgroup; index++) {
        uint elementId = gl_WorkGroupID.x * g_num_blocks_per_workgroup * WORKGROUP_SIZE + index * WORKGROUP_SIZE + gl_LocalInvocationID.x;
        if (elementId < g_num_elements) {
            // determine the bin
            const uint bin = uint(g_elements_in[elementId] >> g_shift) & uint(RADIX_SORT_BINS - 1);
            // increment the histogram
            atomicAdd(histogram[bin], 1U);
        }
    }
    barrier();

    if (gl_LocalInvocationID.x < RADIX_SORT_BINS) {
        g_histograms[RADIX_SORT_BINS * gl_WorkGroupID.x + gl_LocalInvocationID.x] = histogram[gl_LocalInvocationID.x];
    }
}