/**
* VkRadixSort written by Mirco Werner: https://github.com/MircoWerner/VkRadixSort
* Based on implementation of Intel's Embree: https://github.com/embree/embree/blob/v4.0.0-ploc/kernels/rthwif/builder/gpu/sort.h
*/
#version 460
#extension GL_GOOGLE_include_directive: enable
#extension GL_KHR_shader_subgroup_basic: enable
#extension GL_KHR_shader_subgroup_arithmetic: enable

// constraints
// 1. WORKGROUP_SIZE must be a multiple of 32
// 2. WORKGROUP_SIZE >= RADIX_SORT_BINS
// 3. RADIX_SORT_BINS >= SUBGROUP_SIZE
// 4. SUBGROUP_SIZE must match the vendor specific gl_SubgroupSize (e.g., 32 on NVIDIA), you can query this: https://docs.vulkan.org/refpages/latest/refpages/source/VkPhysicalDeviceSubgroupProperties.html
// Adjusting the RADIX_SORT_BINS requires updating the scheduling of the passes on the host side!
layout (local_size_x_id = 0, local_size_x = 256) in; // 256 is the default value, you can update specialization constant 0 from host side
#define WORKGROUP_SIZE gl_WorkGroupSize.x
layout (constant_id = 1) const uint RADIX_SORT_BINS = 256; // 256 is the default value, you can update specialization constant 1 from host side
layout (constant_id = 2) const uint SUBGROUP_SIZE = 32; // 32 is the default value (NVIDIA only!), you can update specialization constant 2 from host side
layout (constant_id = 3) const uint ITERATIONS = 4; // 4 is the default value, you can update specialization constant 3 from host side

layout (push_constant, std430) uniform PushConstants {
    uint g_num_elements;
};

layout (std430, set = 0, binding = 0) buffer elements_in {
    uint g_elements_in[];
};

layout (std430, set = 0, binding = 1) buffer elements_out {
    uint g_elements_out[];
};

shared uint[RADIX_SORT_BINS] histogram;
shared uint[RADIX_SORT_BINS / SUBGROUP_SIZE] sums;// subgroup reductions
shared uint[RADIX_SORT_BINS] local_offsets;// local exclusive scan (prefix sum) (inside subgroups)
shared uint[RADIX_SORT_BINS] global_offsets;// global exclusive scan (prefix sum)

struct BinFlags {
    uint flags[WORKGROUP_SIZE / 32];
};
shared BinFlags[RADIX_SORT_BINS] bin_flags;

#define ELEMENT_IN(index, iteration) (iteration % 2 == 0 ? g_elements_in[index] : g_elements_out[index])

void main() {
    for (uint iteration = 0; iteration < ITERATIONS; iteration++) {
//        const uint shift = 8 * iteration;
        const uint bits_per_pass = findMSB(RADIX_SORT_BINS); // 8 if RADIX_SORT_BINS is 256
        const uint shift = bits_per_pass * iteration;

        // initialize histogram
        if (gl_LocalInvocationID.x < RADIX_SORT_BINS) {
            histogram[gl_LocalInvocationID.x] = 0U;
        }
        barrier();

        for (uint ID = gl_LocalInvocationID.x; ID < g_num_elements; ID += WORKGROUP_SIZE) {
            // determine the bin
            const uint bin = uint(ELEMENT_IN(ID, iteration) >> shift) & uint(RADIX_SORT_BINS - 1);
            // increment the histogram
            atomicAdd(histogram[bin], 1U);
        }
        barrier();

        // subgroup reductions and subgroup prefix sums
        uint histogram_count = 0;
        if (gl_LocalInvocationID.x < RADIX_SORT_BINS) {
            histogram_count = histogram[gl_LocalInvocationID.x];
        }
        uint sum = subgroupAdd(histogram_count);
        uint prefix_sum = subgroupExclusiveAdd(histogram_count);
        if (gl_LocalInvocationID.x < RADIX_SORT_BINS) {
            local_offsets[gl_LocalInvocationID.x] = prefix_sum;
        }
        if (subgroupElect()) {
            // only the elected thread of a subgroup writes to the array
            if (gl_SubgroupID < (RADIX_SORT_BINS / SUBGROUP_SIZE)) {
                // check if the subgroup ID is within the sums array bounds
                sums[gl_SubgroupID] = sum;
            }
        }

        barrier();

        // global prefix sums (offsets)
        if (gl_SubgroupID == 0) {
            uint offset = 0;
            for (uint i = gl_SubgroupInvocationID; i < RADIX_SORT_BINS; i += SUBGROUP_SIZE) {
                global_offsets[i] = offset + local_offsets[i];
                offset += sums[i / SUBGROUP_SIZE];
            }
        }
        barrier();

        //     ==== scatter keys according to global offsets =====
        const uint flags_bin = gl_LocalInvocationID.x / 32;
        const uint flags_bit = 1 << (gl_LocalInvocationID.x % 32);

        for (uint blockID = 0; blockID < g_num_elements; blockID += WORKGROUP_SIZE) {
            barrier();

            const uint ID = blockID + gl_LocalInvocationID.x;

            // initialize bin flags
            if (gl_LocalInvocationID.x < RADIX_SORT_BINS) {
                for (int i = 0; i < WORKGROUP_SIZE / 32; i++) {
                    bin_flags[gl_LocalInvocationID.x].flags[i] = 0U;// init all bin flags to 0
                }
            }
            barrier();

            uint element_in = 0;
            uint binID = 0;
            uint binOffset = 0;
            if (ID < g_num_elements) {
                element_in = ELEMENT_IN(ID, iteration);
                binID = uint((element_in >> shift)) & uint(RADIX_SORT_BINS - 1);
                // offset for group
                binOffset = global_offsets[binID];
                // add bit to flag
                atomicAdd(bin_flags[binID].flags[flags_bin], flags_bit);
            }
            barrier();

            if (ID < g_num_elements) {
                // calculate output index of element
                uint prefix = 0;
                uint count = 0;
                for (uint i = 0; i < WORKGROUP_SIZE / 32; i++) {
                    const uint bits = bin_flags[binID].flags[i];
                    const uint full_count = bitCount(bits);
                    const uint partial_count = bitCount(bits & (flags_bit - 1));
                    prefix += (i < flags_bin) ? full_count : 0U;
                    prefix += (i == flags_bin) ? partial_count : 0U;
                    count += full_count;
                }
                if (iteration % 2 == 0) {
                    g_elements_out[binOffset + prefix] = element_in;
                } else {
                    g_elements_in[binOffset + prefix] = element_in;
                }
                if (prefix == count - 1) {
                    atomicAdd(global_offsets[binID], count);
                }
            }
        }
    }
}